### ISSUE TITLE
C9 Installation Error

### ISSUE THREAD

**Issue by dfdx2** [codefordc/ancfinder#148] opened 2015-11-23 01:18 UTC
I had deleted my C9 account by mistake and when trying to set up ANCFINDER again I got this error meesage after running _sh c9provision.sh_ 

``` python
    Running a local deployment...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named registration
```

**Comment by stvnrlly** [comment] 2015-12-01 17:38
It looks like something is wrong with the submodule. I don't know what the problem is there (it may be something we did in the last pull request), but you can fix it with these steps:

```
cd ext
rm -rf django-registration-pv
git clone git@github.com:JoshData/django-registration-pv.git
```

That will give you a fresh copy of the submodule to work with and allows everything to run properly.

**Comment by mkalish** [comment] 2018-08-07 23:47
Closing this since the issue seems to be resolved.

**Closed by mkalish** 2018-08-07 23:47 UTC
